name: YukiReplay
main: moe.protasis.replay.YukiReplay
version: 1.0
author: KuromeSama6

depend:
  - coreutils
  - NPCLibPlugin

commands:
  replaydebug:
    usage: replaydebug
    description: replay debug command
    permission: replay.debug